### PR TITLE
feat(format): support text format in console with color

### PR DESCRIPTION
**Pull request by vincenthou**
This is helpful in CI building

### CODE REVIEW

**Comment by wgliang** [comment]
Very Cool !

**Comment by wgliang** [comment]
But why do you remove the template parameters.

**Comment by wgliang** [comment]
I think the user should have the right to customize the template.

**Comment by wgliang** [comment]
@vincenthou

**Comment by vincenthou** [comment]
@wgliang I only remove the parameter in `NewReporter` funciton, it seems that it is not used in it, it seems that it is only useful for `SaveAsHtml` method

```
// Original funciton signature
func NewReporter(templateHtml string) *Reporter {
	return &Reporter{
		Metrics: make(map[string]Metric, 0),
		syncRW:  new(sync.RWMutex),
	}
}

// main.go
tools.SaveAsHtml(htmlData, *project, *report, startTime, templateHtml)
```

**Comment by wgliang** [comment]
Ok , I get! A good job!

**Pull request merged**
